### ISSUE TITLE
APIv2 will sunset in 2024

### ISSUE THREAD

**Issue by gjohnhazel** [eonvisualmedia/laravel-klaviyo#3]
Any plans to migrate this to the latest API?

**Comment by mnightingale** [comment]
Yes, but I coudn't tell you when.

It appears Klaviyo have a better PHP SDK for their API these days https://github.com/klaviyo/klaviyo-api-php so perhaps I'll just use that internally then this package is just providing a few Laravelisms - macros, queuing etc.

**Comment by mvysh** [comment]
@mnightingale Are there any plans to update to the new API (because Klaviyo will retire legacy v1/v2 APIs on June 30th, 2024)?

**Comment by mnightingale** [comment]
Work has started on the migration #4 at this stage it is untested against the Klaviyo environment.

Depending on other priorities we are probably looking at completing it sometime within the next couple of weeks.

I think the method signatures should mostly stay the same but the payloads will need updating to what the newer apis expect.

**Comment by dries-dekeersgieter** [comment]
Will there be a new release before June 30th?

**Comment by mnightingale** [comment]
v2.0.0 has been release upgrade the `eonvisualmedia/laravel-klaviyo` dependency to `^2.0`.

See release notes on https://github.com/eonvisualmedia/laravel-klaviyo/releases/tag/2.0.0

For users only using client events, the only change required should be to identify/profile payloads.
For users using server side events or the Klaviyo API directly follow the [migration resources](https://developers.klaviyo.com/en/docs/migration_resources) additionally the first-party package `klaviyo/api` may be of use rather than the HTTP package and constructing your own requests. I decided against using it because it's untyped and this package itself only uses a couple of the APIs.
