### ISSUE TITLE
When '_kx' is used for user identification request isn't applied to the customer

### ISSUE THREAD

**Issue by mvysh** [eonvisualmedia/laravel-klaviyo#5]
I'm testing the updated API for `Klaviyo::track(TrackEvent::make(...))`.
Locally, everything works correctly. After running the API call, track info is added to the customer account.
But when testing on the site, API doesn't add information to the customer. 

When testing locally `__kla_id` cookie doesn't have `$exchange_id` field and the payload is:
```
      ...
     "profile": {
        "data": {
          "type": "profile",
          "attributes": {
            "email": "test@test.co",
            "first_name": "Test",
            "last_name": "Customer",
            "properties": {
              "phone": "5555555555"
            }
          }
        }
      },
     ...
```
and when running from the site:
```
     ...
     "profile": {
        "data": {
          "type": "profile",
          "attributes": {
            "_kx": "J2......................................................."
          }
        }
      },
     ...
```
It looks like the `attributes` field should contain at least an `email` field because the `_kx` is not enough to identify the profile.

**Comment by mnightingale** [comment]
I haven't been able to reproduce this so far, I deleted the `__kla_id` cookie.
Visiting my test site triggers: https://github.com/eonvisualmedia/laravel-klaviyo/blob/08fd8e9b2f9c4632735e7f2bdd0166968d0f9e77/src/View/Creators/InitializeCreator.php#L19-L24

User.php has something similar to:
```php
    public function getKlaviyoIdentity(): array
    {
        return [
            'email'            => $this->email,
            'first_name'   => $this->first_name,
            'last_name'    => $this->last_name,
        ];
    }
```

The client hits https://a.klaviyo.com/client/profiles/?company_id=***** and gets an `exchange_id` back and sets the `__kla_id` cookie.

Reloading the page and `dump(\Klaviyo::getDecodedCookie())` has the exchange ID.

```php
[
  "cid" => "******"
  "$referrer" => array:3 [
    ...
  ]
  "$last_referrer" => array:3 [
    ...
  ]
  "$exchange_id" => "******"
  "$first_name" => "******"
  "$last_name" => ""******""
]
```

`Klaviyo::track` sends a server-side event, which should only really be used if absolutely necessary; I only use them for completed purchase events that I want to prevent clients from blocking the request, everywhere else I use Klaviyo::push(...) usually with macros. So I always send the profile instead of relying on the exchange_id.

I tried `Klaviyo::track(TrackEvent::make('Viewed Page'));` and checking the request on https://www.klaviyo.com/developer-tools/logs I can see the following and it's correctly attributed to the profile so just sending _kx does appear to be supported.

```json
{
  "data": {
    "type": "event",
    "attributes": {
      "properties": [],
      "time": "2024-06-15T14:47:01+01:00",
      "unique_id": "d74b1997-5447-4cd5-9547-f964765c9860",
      "metric": {
        "data": {
          "type": "metric",
          "attributes": {
            "name": "Viewed Page"
          }
        }
      },
      "profile": {
        "data": {
          "type": "profile",
          "attributes": {
            "_kx": "******"
          }
        }
      }
    }
  }
}
```

---

So it appears your problem is just that the `__kla_id` cookie doesn't have the `$exchange_id`, is the payload above from the cookie? It looks very different to the structure I see.

How are you identifying users to set the cookie?
Can you see in the browser network tab the response it gets, i.e. does it get an `$exchange_id`?

**Comment by mvysh** [comment]
Today I retested and everything worked correctly!

My problem (described above) was that if in the `Klaviyo::track(TrackEvent::make(...))` request, only the `_kx ` field was used to identify the customer profile, it did not work correctly. But it worked correctly when standard user fields were used for identification (taken from `User::KlaviyoIdentity()`).

I started this topic because locally everything worked correctly (locally `__kla_id` cookie does not have` $exchange_id`, so the `User::KlaviyoIdentity()` identity was taken). But on the test site there was such a key, so it was used in the payload.

But today I encountered another problem: if I change the user in the system or register / login under a new account, the old value remains in the cookie and all events are recorded for the previous user. I don’t know if this is a bug with Klaviyo or if it needs to be configured somehow additionally on my side.

It looks like this issue can be closed as 'can not reproduce'. If I encounter a strange behavior on the Klaviyo side I will add a comment or re-open it.

Thanks again for your work and support!

**Comment by mnightingale** [comment]
> Today I retested and everything worked correctly!
> 
> My problem (described above) was that if in the `Klaviyo::track(TrackEvent::make(...))` request, only the `_kx ` field was used to identify the customer profile, it did not work correctly. But it worked correctly when standard user fields were used for identification (taken from `User::KlaviyoIdentity()`).
> 
> I started this topic because locally everything worked correctly (locally `__kla_id` cookie does not have` $exchange_id`, so the `User::KlaviyoIdentity()` identity was taken). But on the test site there was such a key, so it was used in the payload.

I'm glad you've got it working, the only other thing I'd suggest for server-side events would be to pass the user to `TrackEvent::make()` rather than hoping the user is already known the Klaviyo.

> But today I encountered another problem: if I change the user in the system or register / login under a new account, the old value remains in the cookie and all events are recorded for the previous user. I don’t know if this is a bug with Klaviyo or if it needs to be configured somehow additionally on my side.

Thats a good idea; release [2.1.0](https://github.com/eonvisualmedia/laravel-klaviyo/releases/tag/2.1.0) will listen for `Illuminate\Auth\Events\Login` events and send a `klaviyo.identify(...)` call even if the cookie is already set.

> It looks like this issue can be closed as 'can not reproduce'. If I encounter a strange behavior on the Klaviyo side I will add a comment or re-open it.
> 
> Thanks again for your work and support!
